server:
  port: 1213
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/your_db_name
    username: root
    password: your_db_password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

razorpay:
  api:
    key: your_razorpay_api_key
    secret: your_razorpay_api_secret
